name: Sync Fork

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          owner: Teahouse-Studios
          head: master
          base: dev/docker
